### ISSUE TITLE
Method 'Enqueue' in type 'Hangfire.Azure.ServiceBusQueue.ServiceBusQueueJobQueue'

### ISSUE THREAD

**Issue by mchudinov** [HangfireIO/Hangfire.Azure.ServiceBusQueue#15]
Method 'Enqueue' in type 'Hangfire.Azure.ServiceBusQueue.ServiceBusQueueJobQueue' from assembly 'Hangfire.Azure.ServiceBusQueue, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

Got this error in .NET Core 2.2 project.
Nuget package version Hangfire.Azure.ServiceBusQueue 4.1.0
What is the problem?

Here is the relevant code from ConfigureServices(IServiceCollection services) method
```csharp     
            var sqlStorage = new     SqlServerStorage(SqlServerConnectionString);
            Action<QueueDescription> configureAction = qd =>
            {
                qd.MaxSizeInMegabytes = 5120;
                qd.DefaultMessageTimeToLive = new TimeSpan(0, 1, 0);
            };

                sqlStorage.UseServiceBusQueues(ServiceBusConnectionString);
                sqlStorage.UseServiceBusQueues(ServiceBusConnectionString, "critical", "default");
                sqlStorage.UseServiceBusQueues(ServiceBusConnectionString, configureAction, "critical", "default");

            sqlStorage.UseServiceBusQueues(new ServiceBusQueueOptions
            {
                ConnectionString = ServiceBusConnectionString,
                Configure = configureAction,
                QueuePrefix = "my-prefix-",
                Queues = new[] { EnqueuedState.DefaultQueue },
                CheckAndCreateQueues = false,
                LoopReceiveTimeout = TimeSpan.FromMilliseconds(500)
            });

            GlobalConfiguration.Configuration.UseStorage(sqlStorage);

            services.AddHangfire(configuration => configuration
                .SetDataCompatibilityLevel(CompatibilityLevel.Version_170)
                .UseSimpleAssemblyNameTypeSerializer()
                .UseRecommendedSerializerSettings()
                .UseSqlServerStorage(SqlServerConnectionString, 
                new SqlServerStorageOptions
                {
                    CommandBatchMaxTimeout = TimeSpan.FromMinutes(5),
                    SlidingInvisibilityTimeout = TimeSpan.FromMinutes(5),
                    QueuePollInterval = TimeSpan.Zero,
                    UseRecommendedIsolationLevel = true,
                    UsePageLocksOnDequeue = true,
                    DisableGlobalLocks = true
                }));

            services.AddHangfireServer();
```

**Comment by gregbowyer84** [comment]
Did you get around this problem?

**Comment by gregbowyer84** [comment]
Anybody?

**Comment by FortuneN** [comment]
Anybody?

**Comment by igbenic** [comment]
Anybody?

**Comment by tobiasschittkowski** [comment]
I have the same problem - the current implementation of Enqueue in this Repo is

https://github.com/HangfireIO/Hangfire.Azure.ServiceBusQueue/blob/392ea69420a02b4a8949619663accf1984c763b9/src/HangFire.Azure.ServiceBusQueue/ServiceBusQueueJobQueue.cs#L69

However, in the current Hangfire definition of the interface IPersistentJobQueue, this definition is only valid if Hangfire is compiled with the FEATURE_TRANSACTIONSCOPE flag

```
#if FEATURE_TRANSACTIONSCOPE
        void Enqueue(System.Data.IDbConnection connection, string queue, string jobId);
#else
        void Enqueue(
            System.Data.Common.DbConnection connection, 
            System.Data.Common.DbTransaction transaction, 
            string queue, 
            string jobId);
#endif
```

https://github.com/HangfireIO/Hangfire/blob/dab0f33d44dccbe7b41196c79d3d4016ab971a7d/src/Hangfire.SqlServer/IPersistentJobQueue.cs#L26-34

This flag is only enabled on net45, but not on net core:

` <PropertyGroup Condition="'$(TargetFramework)'=='net45'">
    <DebugType>full</DebugType>
 <DefineConstants>$(DefineConstants);FEATURE_TRANSACTIONSCOPE;FEATURE_CONFIGURATIONMANAGER</DefineConstants></PropertyGroup>`

https://github.com/HangfireIO/Hangfire/blob/3c6d893023d5d7558d6098e80034865004b73786/src/Hangfire.SqlServer/Hangfire.SqlServer.csproj#L11

**Comment by TiagoBrazSantos** [comment]
I have the same problem here. Someone managed to solve? It seems to me the maintainers abandoned the project.
