### ISSUE TITLE
Not working with new version of Hangfire

### ISSUE THREAD

**Issue by dersia** [HangfireIO/Hangfire.Azure.ServiceBusQueue#4]
Hi there,

because of some bugfixes in Hangfire 1.5.0 we updated Hangfire to the newest Version 1.5.2. But it looks like the interfaces changed and this is not reflected in Hangfire.Azure.ServiceBusQueue

I forked an repaired this and going to create a pull-request for this.

**Comment by barclayadam** [comment]
Thanks for the report. Apologies it's taken a long time to reply, have been on holiday. Version 2.0.0 has been published to NuGet and will be available shortly with support for Hangfire 1.5.
