### ISSUE TITLE
.NETStandard Support

### ISSUE THREAD

**Issue by YZahringer** [HangfireIO/Hangfire.Azure.ServiceBusQueue#7]
Replace [WindowsAzure.ServiceBus](https://github.com/Azure/azure-service-bus) .NET 4.5 library by [Microsoft.Azure.Management.ServiceBus](https://github.com/Azure/azure-service-bus-dotnet) .NETStandard 1.4 library.

**Comment by svachha** [comment]
> Replace [WindowsAzure.ServiceBus](https://github.com/Azure/azure-service-bus) .NET 4.5 library by [Microsoft.Azure.Management.ServiceBus](https://github.com/Azure/azure-service-bus-dotnet) .NETStandard 1.4 library.

is this available now for .net core 2.1?

**Comment by GangRobinNiu** [comment]
Do you have any plan and any ETA to support .net core?

**Comment by hermanho** [comment]
I made a version with netstandard2.0 but I don't know how to modify psake-project.ps1 and appveyor.yml

**Comment by ganySA** [comment]
This would be great......

**Comment by lokeshpeta** [comment]
Do we have a ETA on this?
